# Generated by Django 6.0.6 on 2026-07-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Roll',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
