# Generated by Django 6.0.6 on 2026-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_studentprofile_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_files/'),
        ),
        migrations.AddField(
            model_name='complains',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Complaint_image'),
        ),
        migrations.AddField(
            model_name='complains',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='satisfaction',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Satisfied', 'Satisfed'), ('Non-satisfied', 'Non-satisfied')], default='pending', max_length=20),
        ),
    ]
