# Generated by Django 6.0.6 on 2026-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_complains_file_complains_image_complains_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='Semester',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Semester',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='satisfaction',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Satisfied', 'Satisfed'), ('Non-satisfied', 'Non-satisfied')], default='Pending', max_length=20),
        ),
    ]
