# Generated by Django 6.0.6 on 2026-08-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_complains_semester_complains_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Semester',
        ),
        migrations.AddField(
            model_name='complains',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
