# Generated by Django 6.0.6 on 2026-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_remove_complains_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_hosteler',
            field=models.BooleanField(default=False),
        ),
    ]
